//*
// Flight service.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: path.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Flight message represents source and destination
type Flight struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source      string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destination string `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
}

func (x *Flight) Reset() {
	*x = Flight{}
	if protoimpl.UnsafeEnabled {
		mi := &file_path_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Flight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flight) ProtoMessage() {}

func (x *Flight) ProtoReflect() protoreflect.Message {
	mi := &file_path_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flight.ProtoReflect.Descriptor instead.
func (*Flight) Descriptor() ([]byte, []int) {
	return file_path_proto_rawDescGZIP(), []int{0}
}

func (x *Flight) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Flight) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

// Get request
type GetSortedFlightRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flights []*Flight `protobuf:"bytes,1,rep,name=flights,proto3" json:"flights,omitempty"`
}

func (x *GetSortedFlightRequest) Reset() {
	*x = GetSortedFlightRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_path_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSortedFlightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSortedFlightRequest) ProtoMessage() {}

func (x *GetSortedFlightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_path_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSortedFlightRequest.ProtoReflect.Descriptor instead.
func (*GetSortedFlightRequest) Descriptor() ([]byte, []int) {
	return file_path_proto_rawDescGZIP(), []int{1}
}

func (x *GetSortedFlightRequest) GetFlights() []*Flight {
	if x != nil {
		return x.Flights
	}
	return nil
}

// Get response
type GetSortedFlightResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sorted *Flight `protobuf:"bytes,1,opt,name=sorted,proto3" json:"sorted,omitempty"`
}

func (x *GetSortedFlightResponse) Reset() {
	*x = GetSortedFlightResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_path_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSortedFlightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSortedFlightResponse) ProtoMessage() {}

func (x *GetSortedFlightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_path_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSortedFlightResponse.ProtoReflect.Descriptor instead.
func (*GetSortedFlightResponse) Descriptor() ([]byte, []int) {
	return file_path_proto_rawDescGZIP(), []int{2}
}

func (x *GetSortedFlightResponse) GetSorted() *Flight {
	if x != nil {
		return x.Sorted
	}
	return nil
}

var File_path_proto protoreflect.FileDescriptor

var file_path_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x70, 0x61, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x66, 0x6c,
	0x69, 0x67, 0x68, 0x74, 0x2e, 0x76, 0x31, 0x22, 0x42, 0x0a, 0x06, 0x46, 0x6c, 0x69, 0x67, 0x68,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73,
	0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x45, 0x0a, 0x16, 0x47,
	0x65, 0x74, 0x53, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x07, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x07, 0x66, 0x6c, 0x69, 0x67, 0x68,
	0x74, 0x73, 0x22, 0x44, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x46,
	0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a,
	0x06, 0x73, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74,
	0x52, 0x06, 0x73, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x32, 0x69, 0x0a, 0x0d, 0x46, 0x6c, 0x69, 0x67,
	0x68, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x58, 0x0a, 0x0f, 0x47, 0x65, 0x74,
	0x53, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x12, 0x21, 0x2e, 0x66,
	0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x6f, 0x72, 0x74,
	0x65, 0x64, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x22, 0x2e, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53,
	0x6f, 0x72, 0x74, 0x65, 0x64, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x63, 0x6f, 0x6f, 0x6c, 0x2d, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x2f,
	0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x2d, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x2d, 0x67, 0x6f,
	0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x70, 0x61, 0x74, 0x68, 0x63, 0x74, 0x72, 0x6c, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_path_proto_rawDescOnce sync.Once
	file_path_proto_rawDescData = file_path_proto_rawDesc
)

func file_path_proto_rawDescGZIP() []byte {
	file_path_proto_rawDescOnce.Do(func() {
		file_path_proto_rawDescData = protoimpl.X.CompressGZIP(file_path_proto_rawDescData)
	})
	return file_path_proto_rawDescData
}

var file_path_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_path_proto_goTypes = []interface{}{
	(*Flight)(nil),                  // 0: flight.v1.Flight
	(*GetSortedFlightRequest)(nil),  // 1: flight.v1.GetSortedFlightRequest
	(*GetSortedFlightResponse)(nil), // 2: flight.v1.GetSortedFlightResponse
}
var file_path_proto_depIdxs = []int32{
	0, // 0: flight.v1.GetSortedFlightRequest.flights:type_name -> flight.v1.Flight
	0, // 1: flight.v1.GetSortedFlightResponse.sorted:type_name -> flight.v1.Flight
	1, // 2: flight.v1.FlightService.GetSortedFlight:input_type -> flight.v1.GetSortedFlightRequest
	2, // 3: flight.v1.FlightService.GetSortedFlight:output_type -> flight.v1.GetSortedFlightResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_path_proto_init() }
func file_path_proto_init() {
	if File_path_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_path_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Flight); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_path_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSortedFlightRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_path_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSortedFlightResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_path_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_path_proto_goTypes,
		DependencyIndexes: file_path_proto_depIdxs,
		MessageInfos:      file_path_proto_msgTypes,
	}.Build()
	File_path_proto = out.File
	file_path_proto_rawDesc = nil
	file_path_proto_goTypes = nil
	file_path_proto_depIdxs = nil
}
